const topics = [
  { topicname: "Web Developemnt", mentor: "Prakash", date: "12-10-2020" },
  { topicname: "React", mentor: "Sangeetha", date: "21-10-2020" },
  { topicname: "Data Science", mentor: "Arul", date: "12-11-2020" },
  { topicname: "Internet of Things", mentor: "Shakeel", date: "12-09-2020" },
  { topicname: "Automation Testing", mentor: "Arun", date: "16-11-2020" },
  {
    topicname: "Mobile App Development",
    mentor: "Manikandan",
    date: "30-10-2020",
  },
  { topicname: "UI/UX ", mentor: "Poonam", date: "06-09-2020" },
];

const tasks = [
  { taskname: "React formik", mentor: "Prakash", date: "12-10-2020" },
  { taskname: "javascript map", mentor: "Sangeetha", date: "21-10-2020" },
  { taskname: "sql basics", mentor: "Arul", date: "12-11-2020" },
  { taskname: "Array methods", mentor: "Shakeel", date: "12-09-2020" },
  { taskname: "Async Promise", mentor: "Arun", date: "16-11-2020" },
  {
    taskname: "Async Callback",
    mentor: "Manikandan",
    date: "30-10-2020",
  },
  { taskname: "context API ", mentor: "Poonam", date: "06-09-2020" },
];
const users = [
  {
    id: 1,
    name: "Hari",
    course: "Web Development",
    join_Date: "12-06-2020",
    codekata: 174,
    webkata: 35,
    mentor: "Prakash",
    absentDays: [{ date: "15-06-2020" }, { date: "20-06-2020" }],
    tasks: [
      {
        taskId: "task_id_1",
        status: "Submitted",
        submissionDate: "13-06-2020",
      },
      { taskId: "task_id_2", status: "Not Submitted" },
    ],
  },
  {
    id: 2,
    name: "Ravi",
    course: "UI/UX",
    join_Date: "22-07-2020",
    codekata: 120,
    webkata: 20,
    mentor: "Prakash",
    absentDays: [{ date: "25-07-2020" }, { date: "02-08-2020" }],
    tasks: [
      {
        taskId: "task_id_3",
        status: "Submitted",
        submissionDate: "23-07-2020",
      },
      { taskId: "task_id_4", status: "Not Submitted" },
    ],
  },
  {
    id: 3,
    name: "Sneha",
    course: "App Development",
    join_Date: "15-08-2020",
    codekata: 200,
    webkata: 50,
    mentor: "Prakash",
    absentDays: [{ date: "18-08-2020" }, { date: "25-08-2020" }],
    tasks: [
      {
        taskId: "task_id_5",
        status: "Submitted",
        submissionDate: "17-08-2020",
      },
      { taskId: "task_id_6", status: "Not Submitted" },
    ],
  },
  {
    id: 4,
    name: "Amit",
    course: "Automation Testing",
    join_Date: "30-09-2020",
    codekata: 80,
    webkata: 10,
    mentor: "Prakash",
    absentDays: [{ date: "05-10-2020" }, { date: "10-10-2020" }],
    tasks: [
      {
        taskId: "task_id_7",
        status: "Submitted",
        submissionDate: "01-10-2020",
      },
      { taskId: "task_id_8", status: "Not Submitted" },
    ],
  },
  {
    id: 5,
    name: "Neha",
    course: "IoT",
    join_Date: "05-10-2020",
    codekata: 150,
    webkata: 30,
    mentor: "Prakash",
    absentDays: [{ date: "08-10-2020" }, { date: "15-10-2020" }],
    tasks: [
      {
        taskId: "task_id_9",
        status: "Submitted",
        submissionDate: "07-10-2020",
      },
      { taskId: "task_id_10", status: "Not Submitted" },
    ],
  },
  {
    id: 6,
    name: "Ananya",
    course: "Web Development",
    join_Date: "18-11-2020",
    codekata: 220,
    webkata: 40,
    mentor: "Prakash",
    absentDays: [{ date: "22-11-2020" }, { date: "28-11-2020" }],
    tasks: [
      {
        taskId: "task_id_11",
        status: "Submitted",
        submissionDate: "20-11-2020",
      },
      { taskId: "task_id_12", status: "Not Submitted" },
    ],
  },
  {
    id: 7,
    name: "Vikram",
    course: "UI/UX",
    join_Date: "03-12-2020",
    codekata: 90,
    webkata: 15,
    mentor: "Prakash",
    absentDays: [{ date: "08-12-2020" }, { date: "12-12-2020" }],
    tasks: [
      {
        taskId: "task_id_13",
        status: "Submitted",
        submissionDate: "06-12-2020",
      },
      { taskId: "task_id_14", status: "Not Submitted" },
    ],
  },
  {
    id: 8,
    name: "Priya",
    course: "App Development",
    join_Date: "09-06-2020",
    codekata: 180,
    webkata: 25,
    mentor: "Prakash",
    absentDays: [{ date: "13-06-2020" }, { date: "19-06-2020" }],
    tasks: [
      {
        taskId: "task_id_15",
        status: "Submitted",
        submissionDate: "11-06-2020",
      },
      { taskId: "task_id_16", status: "Not Submitted" },
    ],
  },
  {
    id: 9,
    name: "Aditya",
    course: "Automation Testing",
    join_Date: "21-07-2020",
    codekata: 130,
    webkata: 30,
    mentor: "Prakash",
    absentDays: [{ date: "25-07-2020" }, { date: "30-07-2020" }],
    tasks: [
      {
        taskId: "task_id_17",
        status: "Submitted",
        submissionDate: "23-07-2020",
      },
      { taskId: "task_id_18", status: "Not Submitted" },
    ],
  },
  {
    id: 10,
    name: "Nisha",
    course: "IoT",
    join_Date: "12-08-2020",
    codekata: 110,
    webkata: 20,
    mentor: "Prakash",
    absentDays: [{ date: "18-08-2020" }, { date: "25-08-2020" }],
    tasks: [
      {
        taskId: "task_id_19",
        status: "Submitted",
        submissionDate: "16-08-2020",
      },
      { taskId: "task_id_20", status: "Not Submitted" },
    ],
  },
  {
    id: 11,
    name: "Rahul",
    course: "Web Development",
    join_Date: "28-09-2020",
    codekata: 190,
    webkata: 45,
    mentor: "Prakash",
    absentDays: [{ date: "02-10-2020" }, { date: "08-10-2020" }],
    tasks: [
      {
        taskId: "task_id_21",
        status: "Submitted",
        submissionDate: "30-09-2020",
      },
      { taskId: "task_id_22", status: "Not Submitted" },
    ],
  },
  {
    id: 12,
    name: "Tara",
    course: "UI/UX",
    join_Date: "04-10-2020",
    codekata: 80,
    webkata: 15,
    mentor: "Prakash",
    absentDays: [{ date: "08-10-2020" }, { date: "14-10-2020" }],
    tasks: [
      {
        taskId: "task_id_23",
        status: "Submitted",
        submissionDate: "02-10-2020",
      },
      { taskId: "task_id_24", status: "Not Submitted" },
    ],
  },
  {
    id: 13,
    name: "Ajay",
    course: "App Development",
    join_Date: "16-11-2020",
    codekata: 160,
    webkata: 35,
    mentor: "Prakash",
    absentDays: [{ date: "20-11-2020" }, { date: "26-11-2020" }],
    tasks: [
      {
        taskId: "task_id_25",
        status: "Submitted",
        submissionDate: "18-11-2020",
      },
      { taskId: "task_id_26", status: "Not Submitted" },
    ],
  },
  {
    id: 14,
    name: "Sonia",
    course: "Automation Testing",
    join_Date: "07-12-2020",
    codekata: 120,
    webkata: 20,
    mentor: "Prakash",
    absentDays: [{ date: "12-12-2020" }, { date: "18-12-2020" }],
    tasks: [
      {
        taskId: "task_id_27",
        status: "Submitted",
        submissionDate: "10-12-2020",
      },
      { taskId: "task_id_28", status: "Not Submitted" },
    ],
  },
  {
    id: 15,
    name: "Raj",
    course: "IoT",
    join_Date: "14-06-2020",
    codekata: 150,
    webkata: 25,
    mentor: "Prakash",
    absentDays: [{ date: "19-06-2020" }, { date: "24-06-2020" }],
    tasks: [
      {
        taskId: "task_id_29",
        status: "Submitted",
        submissionDate: "17-06-2020",
      },
      { taskId: "task_id_30", status: "Not Submitted" },
    ],
  },
  {
    id: 16,
    name: "Deepa",
    course: "Web Development",
    join_Date: "23-07-2020",
    codekata: 200,
    webkata: 40,
    mentor: "Prakash",
    absentDays: [{ date: "28-07-2020" }, { date: "02-08-2020" }],
    tasks: [
      {
        taskId: "task_id_31",
        status: "Submitted",
        submissionDate: "26-07-2020",
      },
      { taskId: "task_id_32", status: "Not Submitted" },
    ],
  },
  {
    id: 17,
    name: "Kunal",
    course: "UI/UX",
    join_Date: "29-08-2020",
    codekata: 100,
    webkata: 18,
    mentor: "Prakash",
    absentDays: [{ date: "03-09-2020" }, { date: "08-09-2020" }],
    tasks: [
      {
        taskId: "task_id_33",
        status: "Submitted",
        submissionDate: "01-09-2020",
      },
      { taskId: "task_id_34", status: "Not Submitted" },
    ],
  },
  {
    id: 18,
    name: "Shreya",
    course: "App Development",
    join_Date: "02-09-2020",
    codekata: 130,
    webkata: 25,
    mentor: "Prakash",
    absentDays: [{ date: "06-09-2020" }, { date: "12-09-2020" }],
    tasks: [
      {
        taskId: "task_id_35",
        status: "Submitted",
        submissionDate: "04-09-2020",
      },
      { taskId: "task_id_36", status: "Not Submitted" },
    ],
  },
  {
    id: 19,
    name: "Gaurav",
    course: "Automation Testing",
    join_Date: "14-10-2020",
    codekata: 90,
    webkata: 10,
    mentor: "Prakash",
    absentDays: [{ date: "18-10-2020" }, { date: "23-10-2020" }],
    tasks: [
      {
        taskId: "task_id_37",
        status: "Submitted",
        submissionDate: "16-10-2020",
      },
      { taskId: "task_id_38", status: "Not Submitted" },
    ],
  },
  {
    id: 20,
    name: "Mala",
    course: "IoT",
    join_Date: "25-11-2020",
    codekata: 180,
    webkata: 35,
    mentor: "Prakash",
    absentDays: [{ date: "28-11-2020" }, { date: "04-12-2020" }],
    tasks: [
      {
        taskId: "task_id_39",
        status: "Submitted",
        submissionDate: "27-11-2020",
      },
      { taskId: "task_id_40", status: "Not Submitted" },
    ],
  },
  {
    id: 21,
    name: "Sonia",
    course: "Automation Testing",
    join_Date: "07-12-2020",
    codekata: 120,
    webkata: 20,
    mentor: "Prakash",
    absentDays: [{ date: "12-12-2020" }, { date: "18-12-2020" }],
    tasks: [
      {
        taskId: "task_id_59",
        status: "Submitted",
        submissionDate: "10-12-2020",
      },
      { taskId: "task_id_60", status: "Not Submitted" },
    ],
  },
  {
    id: 22,
    name: "Raj",
    course: "IoT",
    join_Date: "14-06-2020",
    codekata: 150,
    webkata: 25,
    mentor: "Prakash",
    absentDays: [{ date: "18-06-2020" }, { date: "22-06-2020" }],
    tasks: [
      {
        taskId: "task_id_61",
        status: "Submitted",
        submissionDate: "16-06-2020",
      },
      { taskId: "task_id_62", status: "Not Submitted" },
    ],
  },
  {
    id: 23,
    name: "Deepa",
    course: "Web Development",
    join_Date: "23-07-2020",
    codekata: 200,
    webkata: 40,
    mentor: "Prakash",
    absentDays: [{ date: "28-07-2020" }, { date: "02-08-2020" }],
    tasks: [
      {
        taskId: "task_id_63",
        status: "Submitted",
        submissionDate: "25-07-2020",
      },
      { taskId: "task_id_64", status: "Not Submitted" },
    ],
  },
  {
    id: 24,
    name: "Kunal",
    course: "UI/UX",
    join_Date: "29-08-2020",
    codekata: 100,
    webkata: 18,
    mentor: "Prakash",
    absentDays: [{ date: "02-09-2020" }, { date: "08-09-2020" }],
    tasks: [
      {
        taskId: "task_id_65",
        status: "Submitted",
        submissionDate: "05-09-2020",
      },
      { taskId: "task_id_66", status: "Not Submitted" },
    ],
  },
  {
    id: 25,
    name: "Shreya",
    course: "App Development",
    join_Date: "02-09-2020",
    codekata: 130,
    webkata: 25,
    mentor: "Prakash",
    absentDays: [{ date: "07-09-2020" }, { date: "12-09-2020" }],
    tasks: [
      {
        taskId: "task_id_67",
        status: "Submitted",
        submissionDate: "05-09-2020",
      },
      { taskId: "task_id_68", status: "Not Submitted" },
    ],
  },
  {
    id: 26,
    name: "Gaurav",
    course: "Automation Testing",
    join_Date: "14-10-2020",
    codekata: 90,
    webkata: 10,
    mentor: "Prakash",
    absentDays: [{ date: "18-10-2020" }, { date: "22-10-2020" }],
    tasks: [
      {
        taskId: "task_id_69",
        status: "Submitted",
        submissionDate: "16-10-2020",
      },
      { taskId: "task_id_70", status: "Not Submitted" },
    ],
  },
  {
    id: 27,
    name: "Mala",
    course: "IoT",
    join_Date: "25-11-2020",
    codekata: 180,
    webkata: 35,
    mentor: "Prakash",
    absentDays: [{ date: "28-11-2020" }, { date: "02-12-2020" }],
    tasks: [
      {
        taskId: "task_id_71",
        status: "Submitted",
        submissionDate: "27-11-2020",
      },
      { taskId: "task_id_72", status: "Not Submitted" },
    ],
  },
  {
    id: 28,
    name: "Aryan",
    course: "Web Development",
    join_Date: "09-12-2020",
    codekata: 160,
    webkata: 30,
    mentor: "Prakash",
    absentDays: [{ date: "14-12-2020" }, { date: "18-12-2020" }],
    tasks: [
      {
        taskId: "task_id_73",
        status: "Submitted",
        submissionDate: "12-12-2020",
      },
      { taskId: "task_id_74", status: "Not Submitted" },
    ],
  },
  {
    id: 29,
    name: "Arpita",
    course: "UI/UX",
    join_Date: "17-06-2020",
    codekata: 70,
    webkata: 12,
    mentor: "Prakash",
    absentDays: [{ date: "20-06-2020" }, { date: "25-06-2020" }],
    tasks: [
      {
        taskId: "task_id_75",
        status: "Submitted",
        submissionDate: "22-06-2020",
      },
      { taskId: "task_id_76", status: "Not Submitted" },
    ],
  },
  {
    id: 30,
    name: "Manoj",
    course: "App Development",
    join_Date: "20-07-2020",
    codekata: 120,
    webkata: 22,
    mentor: "Prakash",
    absentDays: [{ date: "25-07-2020" }, { date: "30-07-2020" }],
    tasks: [
      {
        taskId: "task_id_77",
        status: "Submitted",
        submissionDate: "23-07-2020",
      },
      { taskId: "task_id_78", status: "Not Submitted" },
    ],
  },
];
const companies = [
  {
    companyName: "ABC Tech",
    recruitmentDate: "2020-10-15",
    attended: 30,
    selectedCount: 3,
    selected: ["Hari", "Ravi", "Sneha"],
  },
  {
    companyName: "XYZ Solutions",
    recruitmentDate: "2020-10-20",
    attended: 25,
    selectedCount: 2,
    selected: ["Ravi", "Sneha"],
  },
  {
    companyName: "Tech Innovators",
    recruitmentDate: "2020-11-05",
    attended: 20,
    selectedCount: 1,
    selected: ["Hari"],
  },
  {
    companyName: "Future Systems",
    recruitmentDate: "2020-11-10",
    attended: 15,
    selectedCount: 3,
    selected: ["Sneha", "Amit", "Neha"],
  },
  {
    companyName: "Infinite Dynamics",
    recruitmentDate: "2020-11-18",
    attended: 28,
    selectedCount: 1,
    selected: ["Ananya"],
  },
  {
    companyName: "Swift Solutions",
    recruitmentDate: "2020-11-22",
    attended: 22,
    selectedCount: 2,
    selected: ["Ravi", "Sneha"],
  },
  {
    companyName: "CodeCrafters",
    recruitmentDate: "2020-10-03",
    attended: 18,
    selectedCount: 3,
    selected: ["Hari", "Ravi", "Sneha"],
  },
  {
    companyName: "Data Dynamics",
    recruitmentDate: "2020-10-12",
    attended: 24,
    selectedCount: 1,
    selected: ["Hari"],
  },
  {
    companyName: "TechVibes",
    recruitmentDate: "2020-10-28",
    attended: 30,
    selectedCount: 2,
    selected: ["Sneha", "Amit"],
  },
  {
    companyName: "InnoTech Solutions",
    recruitmentDate: "2020-11-07",
    attended: 16,
    selectedCount: 1,
    selected: ["Ravi"],
  },
  {
    companyName: "NexGen Innovations",
    recruitmentDate: "2020-11-14",
    attended: 20,
    selectedCount: 3,
    selected: ["Ananya", "Vikram", "Priya"],
  },
  {
    companyName: "CodeMasters",
    recruitmentDate: "2020-10-17",
    attended: 25,
    selectedCount: 2,
    selected: ["Ravi", "Sneha"],
  },
  {
    companyName: "FutureTech",
    recruitmentDate: "2020-10-25",
    attended: 18,
    selectedCount: 1,
    selected: ["Hari"],
  },
  {
    companyName: "InnoSolutions",
    recruitmentDate: "2020-11-09",
    attended: 22,
    selectedCount: 3,
    selected: ["Sneha", "Amit", "Neha"],
  },
  {
    companyName: "Digital Dreams",
    recruitmentDate: "2020-11-21",
    attended: 26,
    selectedCount: 2,
    selected: ["Ravi", "Sneha"],
  },
];
const mentors = [
  {
    id: 1,
    name: "Prakash",
    students: ["Hari", "Ravi", "Sneha", "Amit", "Neha"],
    courseOpted: "Web Development",
    joiningDate: "10-09-2020",
  },
  {
    id: 2,
    name: "Suman",
    students: ["Ananya", "Vikram", "Priya", "Aditya", "Nisha"],
    courseOpted: "UI/UX",
    joiningDate: "15-10-2020",
  },
  {
    id: 3,
    name: "Divya",
    students: ["Gaurav", "Mala", "Aryan", "Arpita", "Manoj"],
    courseOpted: "App Development",
    joiningDate: "20-11-2020",
  },
  {
    id: 4,
    name: "Rajesh",
    students: ["Sonia", "Raj", "Deepa", "Kunal", "Shreya"],
    courseOpted: "Automation Testing",
    joiningDate: "05-12-2020",
  },
  {
    id: 5,
    name: "Nivedita",
    students: [
      "Aditi",
      "Alok",
      "Swati",
      "Rohan",
      "Shivani",
      "Sonia",
      "Raj",
      "Deepa",
      "Kunal",
      "Shreya",
      "Prateek",
      "Isha",
      "Rahul",
      "Pooja",
      "Tanvi",
      "Gaurav",
      "Mala",
      "Aryan",
    ],
    courseOpted: "IoT",
    joiningDate: "10-01-2021",
  },
  {
    id: 6,
    name: "Amita",
    students: ["Prateek", "Isha", "Rahul", "Pooja", "Tanvi"],
    courseOpted: "Web Development",
    joiningDate: "15-02-2021",
  },
  {
    id: 7,
    name: "Suresh",
    students: [
      "Jyoti",
      "Adarsh",
      "Anita",
      "Rohit",
      "Kavita",
      "Sonia",
      "Kunal",
      "Shreya",
    ],
    courseOpted: "UI/UX",
    joiningDate: "20-03-2021",
  },
  {
    id: 8,
    name: "Priyanka",
    students: ["Varun", "Sakshi", "Alok", "Kritika", "Rohit"],
    courseOpted: "App Development",
    joiningDate: "25-04-2021",
  },
  {
    id: 9,
    name: "Vikas",
    students: [
      "Sonam",
      "Sagar",
      "Ishita",
      "Amit",
      "Vishal",
      "Varun",
      "Sakshi",
      "Alok",
    ],
    courseOpted: "Automation Testing",
    joiningDate: "30-05-2021",
  },
  {
    id: 10,
    name: "Shikha",
    students: ["Rohan", "Aishwarya", "Karan", "Naina", "Rahul"],
    courseOpted: "IoT",
    joiningDate: "05-06-2021",
  },
  {
    id: 11,
    name: "Harish",
    students: ["Anjali", "Manish", "Shreya", "Parth", "Kavita"],
    courseOpted: "Web Development",
    joiningDate: "10-07-2021",
  },
  {
    id: 12,
    name: "Preeti",
    students: ["Kunal", "Meera", "Alok", "Akanksha", "Sachin"],
    courseOpted: "UI/UX",
    joiningDate: "15-08-2021",
  },
  {
    id: 13,
    name: "Rajat",
    students: ["Mansi", "Pratik", "Aditi", "Rahul", "Divya"],
    courseOpted: "App Development",
    joiningDate: "20-09-2021",
  },
  {
    id: 14,
    name: "Vidya",
    students: ["Yash", "Nisha", "Amit", "Sagar", "Ruchi"],
    courseOpted: "Automation Testing",
    joiningDate: "25-10-2021",
  },
  {
    id: 15,
    name: "Arun",
    students: [
      "Sakshi",
      "Rohit",
      "Ankita",
      "Parth",
      "Neha",
      "Varun",
      "Sakshi",
      "Alok",
    ],
    courseOpted: "IoT",
    joiningDate: "30-11-2021",
  },
  {
    id: 16,
    name: "Naina",
    students: ["Rahul", "Jyoti", "Ankit", "Tanvi", "Sagar"],
    courseOpted: "Web Development",
    joiningDate: "05-12-2021",
  },
  {
    id: 17,
    name: "Ravi",
    students: ["Alok", "Shikha", "Rahul", "Priya", "Sagar"],
    courseOpted: "UI/UX",
    joiningDate: "10-01-2022",
  },
  {
    id: 18,
    name: "Ankush",
    students: [
      "Divya",
      "Suresh",
      "Amit",
      "Tanvi",
      "Neha",
      "Varun",
      "Sakshi",
      "Alok",
    ],
    courseOpted: "App Development",
    joiningDate: "15-02-2022",
  },
  {
    id: 19,
    name: "Pooja",
    students: ["Rahul", "Jyoti", "Pratik", "Tanvi", "Sagar"],
    courseOpted: "Automation Testing",
    joiningDate: "20-03-2022",
  },
  {
    id: 20,
    name: "Vishal",
    students: ["Sakshi", "Rohit", "Ankita", "Parth", "Neha"],
    courseOpted: "IoT",
    joiningDate: "25-04-2022",
  },
];
